import { useEffect } from 'react';
import { useNavigate } from 'react-router';
import { useAppContext } from '../context/AppContext';
import { ChevronLeft } from 'lucide-react';

export default function ApplicationLetter() {
  const navigate = useNavigate();
  const { teamLeader, teamMembers, selectedGuide, teamId } = useAppContext();

  useEffect(() => {
    const handleBackNavigation = () => {
      navigate('/', { replace: true });
    };

    window.history.pushState(null, '', window.location.href);
    window.addEventListener('popstate', handleBackNavigation);

    return () => {
      window.removeEventListener('popstate', handleBackNavigation);
    };
  }, [navigate]);

  // Combine team leader and members
  const allMembers = teamLeader ? [teamLeader, ...teamMembers] : teamMembers;

  // Calculate stream diversity
  const streams = new Set(allMembers.map(m => m.stream));
  const streamArray = Array.from(streams);

  // Get current date
  const currentDate = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric'
  });

  // Use team ID from context (generated by backend)
  const displayTeamId = teamId || 'PENDING';

  return (
    <div className="bg-[#e9e9e9] relative w-full min-h-screen pb-[40px] print:pb-0 print:bg-white">
      {/* Navigation Header - Hidden in print */}
      <div className="print:hidden relative w-full max-w-[210mm] mx-auto px-4 sm:px-6">
        <div className="flex items-center justify-between pt-[16px] pb-[20px]">
          <div className="flex items-center">
            <button 
              onClick={() => navigate('/', { replace: true })}
              className="w-[30px] h-[42px] cursor-pointer flex items-center justify-center mr-2"
            >
              <ChevronLeft size={30} className="text-[#3b3b3b]" strokeWidth={2.5} />
            </button>
            <p className="font-['Cormorant',serif] font-bold leading-[64px] text-[#3b3b3b] text-[57px]">
              IP
            </p>
          </div>
          <button
            onClick={() => window.print()}
            className="px-6 h-[40px] bg-black rounded-[10px] font-['Inter',sans-serif] font-semibold text-[#e9e9e9] text-[13px] hover:bg-gray-800 transition-colors active:scale-95"
            title="Save as PDF - works on mobile and desktop"
          >
            Save as PDF
          </button>
        </div>
      </div>

      {/* Application Letter - A4 Size (Desktop view on mobile too) */}
      <div className="relative w-full min-w-[210mm] max-w-[210mm] mx-auto bg-white shadow-lg print:shadow-none print:max-w-full overflow-x-auto sm:overflow-visible">
        {/* Page 1 */}
        <div className="print:min-h-[297mm] print:page-break-after-always">
          {/* Header */}
          <div className="border-b-2 border-[#171717] px-[25px] py-[16px] print:px-[20mm] print:py-[5mm]">
            <div className="flex items-baseline justify-between mb-[6px]">
              <h1 className="font-['Cormorant',serif] font-bold text-[#3b3b3b] text-[30px] leading-[36px] print:text-[26px] print:leading-[32px]">
                Interdisciplinary Project
              </h1>
              <p className="font-['Cabin',sans-serif] text-[#999999] text-[12px]">
                AY 2025-26
              </p>
            </div>
            <p className="font-['Cabin',sans-serif] text-[#999999] text-[14px] mb-[10px]">
              Team Registration Form
            </p>
            <div className="flex justify-between items-center">
              <div>
                <p className="font-['Inter',sans-serif] text-[#3b3b3b] text-[10px] mb-[2px]">
                  <span className="font-semibold">Team ID:</span> {displayTeamId}
                </p>
                <p className="font-['Inter',sans-serif] text-[#999999] text-[9px]">
                  Date: {currentDate}
                </p>
              </div>
            </div>
          </div>

          {/* Content */}
          <div className="px-[25px] py-[16px] print:px-[20mm] print:py-[4mm]">
            {/* Team Information Box */}
            <div className="mb-[12px] pb-[8px] border-b border-[#e0e0e0]">
              <div className="flex gap-2 flex-wrap">{streamArray.map((stream, index) => (
                  <span
                    key={index}
                    className="px-[10px] py-[3px] bg-[#171717] rounded-[6px] font-['Inter',sans-serif] text-[9px] font-medium text-white"
                  >
                    {stream}
                  </span>
                ))}
                <span className="px-[10px] py-[3px] bg-white border border-[#171717] rounded-[6px] font-['Inter',sans-serif] text-[9px] font-medium text-[#171717]">
                  {streams.size} Streams
                </span>
              </div>
            </div>

            {/* Team Members */}
            <div className="mb-[12px]">
              <h2 className="font-['Cabin',sans-serif] font-semibold text-[#3b3b3b] text-[15px] mb-[8px]">
                Team Members
              </h2>
              
              <div className="space-y-[6px]">{allMembers.map((member, index) => (
                  <div key={index} className="flex items-center gap-[10px] border border-[#e0e0e0] rounded-[8px] p-[8px]">
                    {/* Number */}
                    <div className="flex-shrink-0 w-[24px] h-[24px] bg-[#171717] rounded-full flex items-center justify-center">
                      <span className="font-['Inter',sans-serif] font-bold text-white text-[10px]">
                        {index + 1}
                      </span>
                    </div>
                    
                    {/* Details */}
                    <div className="flex-1 min-w-0">
                      <p className="font-['Cabin',sans-serif] font-semibold text-[#3b3b3b] text-[11px] mb-[2px]">
                        {member.name} {index === 0 && <span className="font-['Inter',sans-serif] text-[#999999] text-[9px] font-normal">(Team Lead)</span>}
                      </p>
                      <p className="font-['Inter',sans-serif] text-[#999999] text-[9px]">
                        {member.usn}
                      </p>
                    </div>

                    {/* Stream and Section */}
                    <div className="flex-shrink-0 w-[150px]">
                      <p className="font-['Inter',sans-serif] text-[#999999] text-[7px] uppercase tracking-wide mb-[3px]">
                        Stream
                      </p>
                      <div className="flex flex-col gap-1">
                        <span className="inline-block px-[8px] py-[2px] bg-white border border-[#171717] rounded-[5px] font-['Inter',sans-serif] text-[9px] text-[#171717] font-medium w-fit">
                          Sec {member.section || 'N/A'}
                        </span>
                        <span className="font-['Inter',sans-serif] text-[#3b3b3b] text-[8px] leading-[10px]">
                          {member.stream}
                        </span>
                      </div>
                    </div>

                    {/* Signature Space */}
                    <div className="flex-shrink-0 w-[90px]">
                      <div className="border-b border-[#171717] h-[26px] mb-[2px]"></div>
                      <p className="font-['Inter',sans-serif] text-[#999999] text-[7px] text-center">
                        Signature
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Faculty Guide Details */}
            {selectedGuide && (
              <div className="mb-[12px] pb-[12px] border-b border-[#e0e0e0]">
                <h2 className="font-['Cabin',sans-serif] font-semibold text-[#3b3b3b] text-[15px] mb-[8px]">
                  Faculty Guide
                </h2>
                
                <div className="border border-[#e0e0e0] rounded-[8px] p-[8px]">
                  <div className="grid grid-cols-2 gap-x-8 gap-y-[8px]">
                    <div>
                      <p className="font-['Inter',sans-serif] text-[#999999] text-[9px] uppercase tracking-wide mb-[3px]">
                        Name
                      </p>
                      <p className="font-['Cabin',sans-serif] text-[#3b3b3b] text-[13px] font-semibold">
                        {selectedGuide.name}
                      </p>
                    </div>
                    <div>
                      <p className="font-['Inter',sans-serif] text-[#999999] text-[9px] uppercase tracking-wide mb-[3px]">
                        Department
                      </p>
                      <p className="font-['Cabin',sans-serif] text-[#3b3b3b] text-[13px]">
                        {selectedGuide.department}
                      </p>
                    </div>

                  </div>

                  {/* Guide Signature */}
                  <div className="mt-[12px] pt-[10px] border-t border-[#e0e0e0]">
                    <p className="font-['Inter',sans-serif] text-[#999999] text-[9px] uppercase tracking-wide mb-[8px]">
                      Faculty Guide Signature
                    </p>
                    <div className="flex gap-8">
                      <div className="flex-1">
                        <div className="border-b border-[#171717] h-[35px] mb-[3px]"></div>
                        <p className="font-['Inter',sans-serif] text-[#999999] text-[8px]">
                          Signature
                        </p>
                      </div>
                      <div className="flex-1">
                        <div className="border-b border-[#171717] h-[35px] mb-[3px]"></div>
                        <p className="font-['Inter',sans-serif] text-[#999999] text-[8px]">
                          Date
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Declaration */}
            <div className="mb-[8px]">
              <h2 className="font-['Cabin',sans-serif] font-semibold text-[#3b3b3b] text-[15px] mb-[8px]">
                Declaration
              </h2>
              
              <div className="bg-[#f9f9f9] border border-[#e0e0e0] rounded-[8px] p-[10px]">
                <p className="font-['Inter',sans-serif] text-[#3b3b3b] text-[11px] leading-[18px]">
                  We, the undersigned members, hereby declare that our team satisfies the interdisciplinary requirement with members from {streams.size} different stream(s), we have obtained consent from {selectedGuide?.name || 'N/A'} to supervise our project, we agree to comply with all regulations governing the Interdisciplinary Project programme, and the team lead, {teamLeader?.name || 'N/A'}, will serve as the primary point of contact for all official communications.
                </p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="border-t border-[#e0e0e0] px-[25px] py-[8px] print:px-[20mm] print:py-[3mm]">
            <p className="font-['Inter',sans-serif] text-[#999999] text-[9px] text-center">
              Office of Academic Affairs • Interdisciplinary Project Programme • Academic Year 2025-26
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}